### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/CDD-256/A\\filenames.txt'

### ISSUE THREAD

**Issue by Crawlling** [wgcban/ddpm-cd#4] opened 2022-07-19 05:24 UTC
22-07-19 12:54:06.763 - INFO: Cd Model [CD] is created.
22-07-19 12:54:06.763 - INFO: Begin Model Evaluation (testing).
Traceback (most recent call last):
  File "D:\test\ddpm-cd-master\ddpm_cd.py", line 326, in <module>
    for current_step, test_data in enumerate(test_loader):
  File "C:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "C:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "C:\Anaconda3\envs\torch\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\test\ddpm-cd-master\data\CDDataset.py", line 65, in __getitem__
    img_A   = Image.open(A_path).convert("RGB")
  File "C:\Anaconda3\envs\torch\lib\site-packages\PIL\Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/CDD-256/A\\filenames.txt'

i try all of the model is great but just CDD-test happen this.bother again.

**Comment by wgcban** [comment] 2022-07-19 13:19
<img width="685" alt="Screen Shot 2022-07-19 at 9 18 29 AM" src="https://user-images.githubusercontent.com/38159198/179759813-15bd6f06-1a17-4dcc-a90b-030bb000a59f.png">
You can see the first row has "filenames.txt". Please delete that row and try again.

**Comment by wgcban** [comment] 2022-07-19 13:20
Thank you for pointing out this bug. I will update the dataset files to avoid this error in the future.

**Comment by Crawlling** [comment] 2022-07-20 01:39
> Thank you for pointing out this bug. I will update the dataset files to avoid this error in the future.

Thank you for your patience and reply,It is my pleasure to point out the bug.

**Comment by wgcban** [comment] 2022-07-20 01:46
I think the problem is resolved now, so I am closing this issue.

**Comment by wgcban** [comment] 2022-07-20 01:46
I think the problem is resolved now, so I am closing this issue.

**Closed by wgcban** 2022-07-20 01:46 UTC
Labels: bug
